### ISSUE TITLE
DetailEdit

### ISSUE THREAD

**Issue by yus0l** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#108]
### Descrpiton
(작업의 상세 설명을 적어주세요!)
 
### Todo
- [x] 워치 백그라운드 변경
- [x] 에셋 컬러 값 변경
- [x] 리스트 뷰 Emphty 상태일 때, 일러스트 추가 
- [x] iOS에서 컬러 에셋 추가
- [x] UI Icon Asset 추가
