### ISSUE TITLE
CoreData 구조 변경하기

### ISSUE THREAD

**Issue by rokdam** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#121]
### Descrpiton
- 현재 프로젝트에 있는 Model 디렉토리는 수정하지 않음
- CoreData 디렉토리에 있는 구조가 완벽하지 않음. 변경해야 함.
- Note구조체가 대부분의 정보를 가져야 함
- 변환된 xml 파일을 구조에 맞게 데이터 저장될 수 있는 로직을 만들면 됨

### Todo
- [ ] CoreData 디렉토리에 있는 Note 구조 변경
- [ ] xml 을 함수 통해서 데이터 저장하기
- [ ] 현재 테스트로 들어있는 Moon River, 붉은 노을 기준으로 저장해보기
