### ISSUE TITLE
musicXML에 맞춰 진동 시퀀스 생성

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#13]
### Descrpiton

musicXML에 맞춰 진동 시퀀스 생성

### Todo

- [ ] 진동 시퀀스 구조 만들기
- [ ] musicXML에 맞춰 진동 시퀀스 생성
- [ ] 마디 별로 관리
- [ ] 이어서 재생되게 만들기

##학습기대
+ 진동 시퀀스 구조 설계 및 패턴 이해
+ 진동 시퀀스 이어서 재생을 위한 데이터 상태 관리 방법 학습
