### ISSUE TITLE
햅틱 동시성 및 버그 디버깅

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#143]
### Descrpiton

햅틱 동시성 및 버그 디버깅

### Todo

- [ ] 햅틱 동시성
- [ ]  곡 선택 → 재생 → 마디점프 → 재생중 상태에서 리스트뷰 → 다른 곡 재생시 아이폰 상태 초기화 X
- [ ]  연습뷰, 설정뷰에서 bpm → BPM 으로 변경
- [ ]  백그라운드에서 메시지 요청 못 받는 경우 있음
- [ ] 햅틱 off일 때 워치 카운트 다운 안나오게 하기
