### ISSUE TITLE
Design UI 고도화 수정

### ISSUE THREAD

**Issue by yus0l** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#173]
### Descrpiton
하이파이랑 코드상 안 맞는 디자인 디테일 수정하겠습니다.
 
### Todo
- [x] 처음부터 버튼 stroke 컬러 변경
- [x] 이전 마디, 다음 마디 버튼 아이콘 추가 및 변경
- [x] 안쓰는 에셋 정리 
- [x] error, caution, success, info 컬러 추가
