### ISSUE TITLE
연습뷰 하이파이 디자인 반영

### ISSUE THREAD

**Issue by norang00** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#176]
### Descrpiton
연습뷰 디자인의 하이파이 반영
 
### Todo
- [x] [처음으로] 버튼 활성화/비활성화 시의 stroke 컬러 반영
- [x] 악보타이틀 카드 위 뱃지태그 텍스트 폰트 크기 반영
- [x] [이전마디],[다음마디] 버튼의 폰트 크기 반영
