### ISSUE TITLE
연습뷰 워치연결 상태에 따른 툴팁뷰 구현

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#205]
### Descrpiton

연습뷰 워치연결 상태에 따른 툴팁뷰 구현

### Todo

- [ ] 앱이 꺼져있을 때
- [ ] 앱이 설치 안되어 있을 때
- [ ] 앱 백그라운드 세션이 비활성화 상태
- [ ] 워치랑 통신 장애일 때
