### ISSUE TITLE
취소 요청 팝업, 토스트 구현

### ISSUE THREAD

**Issue by isByeolHere** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#207]
### Descrpiton

- 악보 변환뷰 버튼별 추가 뷰 완성
- header 분기처리

### Todo

- [ ] 취소 요청 버튼 누르면 확인 팝업 후 취소되도록 함수 구조 만들기
- [ ] 취소되거나 추가되었을 때 토스트 띄우기
- [ ] header 수량 없을때 안뜨도록 분기처리
