### ISSUE TITLE
Storyboard 삭제

### ISSUE THREAD

**Issue by norang00** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#23]
### Descrpiton

UIKit 에서 사용하지 않는 Storyboard 를 삭제합니다.

### Todo

- [x] 1. Main.storyboard 파일 삭제
- [x] 2. Info.plist에서 스토리보드 관련 설정 제거
- [x] 3. SceneDelegate 에 초기화 코드 추가
- [x] 4. Deployment Info에서 스토리보드 제거 확인
