### ISSUE TITLE
조 이동 관련 구현

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#269]
### Descrpiton

조 이동 관련 구현

### Todo

- [ ] 셋팅 뷰에 샘플 notes 전달 
- [ ] 셋팅뷰에 미리듣기 구현
- [ ] 연습뷰에서 설정된 조에 맞게 midi파일 만들기
