### ISSUE TITLE
음악요청상태 에러 상태와 추가 동작 기능 구현

### ISSUE THREAD

**Issue by isByeolHere** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#276]
### Descrpiton

- 음악 변환 요청시 에러 상태 추가

### Todo

- [ ] 음악 변환 요청후 서버에서 에러값 받으면 띄울 상태 만들기
- [ ] 뷰에서 에러메세지 볼 수 있는 알림창 띄우기
- [ ] 알림창에서 추가 동작 구현해서 뷰랑 연결
