### ISSUE TITLE
새로운 알림 도착시 메뉴 뱃지 업데이트

### ISSUE THREAD

**Issue by Hyungeol94** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#288]
### Descrpiton
새로운 알림이 도착했을 때 메뉴에 붉은 점으로 뱃지를 업데이트합니다.

### Todo
- [x] 뱃지 관련 뷰 추가
- [x] 알림 도착 시 뱃지 업데이트 되도록 설정 
- [x] 유저디폴트 관련 로직 추가
