### ISSUE TITLE
에러 디버깅

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#318]
### Descrpiton

에러 사항 디버깅

### Todo

- [ ] bpm모달 내리면 일시정지 오류 확인
- [ ] 셋팅에서 뒤로 갔을 때 안 멈춤 이슈 디버깅
- [ ] 전체적으로 밀림 이슈(통신 환경 문제인지 파악)
