### ISSUE TITLE
PDF 데이터 불러오기 기능

### ISSUE THREAD

**Issue by norang00** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#33]
### Descrpiton

메인뷰에서 버튼을 눌렀을 때 PDF 파일을 선택할 수 있는 창이 띄워지게 합니다.

### Todo

- [x] 메인뷰 버튼 기존 카메라에서 파일 선택 창으로 바꾸기
- [x] 파일 선택 시에 PDF 형식 파일만 표시되게 하기
- [x] 선택한 파일 미리보기 뷰 만들기
