### ISSUE TITLE
아이폰에서 워치로 메세지 보내기

### ISSUE THREAD

**Issue by isByeolHere** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#38]
### Descrpiton

- 아이폰에서 워치로 메세지 보내기

### Todo

- [x] 아이폰에서 워치로 sendmassage 보내기
- [x] 워치에서는 이를 확인하고 잘 받았다는 것을 아이폰이 알도로 하기
- [x] 보내는 메세지는 제목인 string, 시작시간인 date, 진동 시퀀스 [int] 배열
- [x] 결국 이를 string으로 만들어서 보내야함으로 아이폰에서 데이터를 string으로 만들고
워치에서는 string을 받았을때 원래 자료형으로 다시 만들어야함.
