### ISSUE TITLE
Asset 추가

### ISSUE THREAD

**Issue by yus0l** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#43]
### Descrpiton
UI에 필요한 Asset들을 추가합니다.
 
### Todo
- [x] 컬러 에셋 추가
- [x] 로티 파일 추가
- [ ] 폰트 시스템 추가
- [ ] Icon 에셋 추가
- [ ] 일러스트/이미지 추가
