### ISSUE TITLE
워치 대기뷰 화면 구현 - 아이폰 리스트와 연동

### ISSUE THREAD

**Issue by isByeolHere** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#47]
### Descrpiton

 - 워치 대기뷰 화면 구현
 - 아이폰 리스트 선택 여부를 감지해서 화면 전환.

### Todo

- [ ] 워치 대기뷰 화면 구현
- [ ] 백그라운드 애셋 설정
- [ ] 아이폰 리스트 선택 여부를 감지해서 화면 전환
