### ISSUE TITLE
연습뷰 워치 연결여부,  시작 버튼 요소 연결 및 워치랑 아이폰 동시 재생, 임시 bpm 설정뷰 구현, 아이폰에서 워치 런치 및 워치 조작 연결

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#61]
### Descrpiton

연습뷰 워치 연결여부,  시작 버튼 요소 연결 및 워치랑 아이폰 동시 재생 구현
### Todo

- [x] 워치 연결 여부 연결
- [x] 연습뷰 시작 버튼 연결
- [x] 워치랑 동시 진행 로직 구현
- [x] 아이폰에서 워치앱 런치
- [x] 워치 햅틱실행 로직 조작 아이폰과 연결
