### ISSUE TITLE
XML 파일 보정

### ISSUE THREAD

**Issue by Hyungeol94** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#63]
### Descrpiton
생성된 XML 파일에서 박자가 밀리는 경우가 있습니다. 전체 악보에서 설정된 박자와, 한 마디 내에서의 박자의 합을 더하여 일치하지 않을 경우에 보정하는 로직이 필요합니다.
(작업의 상세 설명을 적어주세요!)

### Todo
- [ ] 악보에서 설정된 박자 구하기
- [ ] 각 마디 내의 합을 구하여 설정된 악보와 일치하는지 확인하기
- [ ] 부족한 경우 쉼표로 채워넣기  
- [ ] 넘친 경우 .. 는 어떻게 할지 논의 필요
