### ISSUE TITLE
Watch 메세지 #2 딕셔너리 구조체 리팩토링

### ISSUE THREAD

**Issue by isByeolHere** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#66]
### Descrpiton
- watch 메세지 딕셔너리 구조체 리팩토링
- reply 대신 UpdatedApplicationContext 이용해서 연결 변경

### Todo

- [ ] watch 메세지 딕셔너리 2번 들어간거 삭제
- [ ] replyHandler 대신 UpdatedApplicationContext 이용해서 연결 변경
- [ ] isReachable → isPaird 로 변경하여 가능한지 확인
