### ISSUE TITLE
네비게이션 연결하기

### ISSUE THREAD

**Issue by norang00** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#67]
### Descrpiton

화면들을 연결하여 플로우를 완성합니다.
navigationController 를 이용하여 메인뷰로 진입, 
리스트의 항목들을 선택하면 상세 연습화면을 표시합니다.

### Todo

- [x] navigationController 루트뷰 설정
- [x] scoreListView 메인뷰로 설정
- [x] 리스트 아이템 선택시 각 연습뷰로 연결
- [x] 설정 아이콘 버튼에 설정뷰 연결
