### ISSUE TITLE
미디어매니저

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MacC-A15-CommandR#9]
### Descrpiton

musicXML 파일을 읽어서 파싱하고 이에 맞게 미디어파일 제작할 수 있도록 mediaMannager 클래스 제작하기

### Todo
- [x] musicXML  조사
- [x] 미디어 파일 생성 기술 조사
- [x] 미디어 파일 bpm 조절 기능 구상
- [x] 1차 musicXML 파싱(음정, 음가, 마디)
- [x] 도3~도4음원 파일 이어서 미디어파일 생성
- [x] 파싱한 데이터로 미디어파일 생성
- [x] 미디어 매니저 구조화

## 학습 기대
+ XMLParser를 다뤄볼 수 있을 것 같다.
+ AVFoundation을 활용해서 미디어 파일 연결방법
+ 최대한 mediaMannager 모듈화 생각하기
+ AudioFormat 탐색
